output "ssh_user" {
  description = "SSH user to login to bastion"
  value       = "${var.ssh_user}"
}

output "security_group_id" {
  description = "ID of the security group the bastion host is launched in"
  value       = "${aws_security_group.bastion.id}"
}

output "asg_id" {
  description = "The ID of the AutoScalingGroup the bastion host is launched within"
  value       = "${aws_autoscaling_group.bastion.id}"
}

output "name" {
  description = "Appname"
  value       = "${module.label.name}"
}

output "tags" {
  description = "Tags generated by label module to apply to other resources"
  value       = "${module.label.tags}"
}
